import type { NextPage } from "next";

import Head from "next/head";
import Image from "next/image";
import PokeGuessApp from "../components/PokeGuessApp";
import TitleBar from "../components/TitleBar";

import axios from "axios";
import { useEffect, useState } from "react";
import styled from "styled-components";

export const StyledBackgroundContainer = styled.div`
  background-image: url("Background.png");
  height: 100vh;
`;

const Home: NextPage = () => {
  const [pokemonRData, setPokemonRData]: any = useState("");
  const [pokemonLData, setPokemonLData]: any = useState(" ");
  const [pokemonQuestion, setPokemonQuestion] = useState("Is Heavier?");

  const randomPokemon: (inUseID?: number) => number = (inUseID) => {
    const pokemonID = Math.floor(Math.random() * 800 + 1);

    if (pokemonID !== inUseID) return pokemonID;
    return randomPokemon(inUseID);
  };

  const generatePokemon = () => {
    const pokemonRight = randomPokemon();
    const pokemonLeft = randomPokemon(pokemonRight);

    return [pokemonRight, pokemonLeft];
  };

  const [pokemonRight, pokemonLeft] = generatePokemon();

  const pokeDataFetch = () => {
    axios.get("/api/pokeapi/" + JSON.stringify(pokemonRight)).then((result) => {
      setPokemonRData(result.data);
    });
    axios.get("/api/pokeapi/" + JSON.stringify(pokemonLeft)).then((result) => {
      setPokemonLData(result.data);
    });
  };

  useEffect(() => {
    pokeDataFetch();
  }, []);

  return (
    <StyledBackgroundContainer>
      <Head>
        <title>The PokeGuess Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TitleBar />
      <PokeGuessApp
        pokemonRImage={pokemonRData.sprite}
        pokemonLImage={pokemonLData.sprite}
        GeneratedQuestion={"test"}
      />
    </StyledBackgroundContainer>
  );
};

export default Home;
