import type { NextPage } from "next";

import Head from "next/head";
import Image from "next/image";
import PokeGuessApp from "../components/PokeGuessApp";
import TitleBar from "../components/TitleBar";

import axios from "axios";
import { useEffect, useState } from "react";
import styled from "styled-components";

export const StyledBackgroundContainer = styled.div`
  background-image: url("Background.png");
  height: 100vh;
`;

const Home: NextPage = () => {
  const [pokemonRData, setPokemonRData]: any = useState("");
  const [pokemonLData, setPokemonLData]: any = useState("");
  const [pokemonQuestion, setPokemonQuestion]: any = useState("");
  const [selectedPokemon, setSelectedPokemon]: any = useState("");

  const randomPokemon: (inUseID?: number) => number = (inUseID) => {
    const pokemonID = Math.floor(Math.random() * 800 + 1);

    if (pokemonID !== inUseID) return pokemonID;
    return randomPokemon(inUseID);
  };

  const generatePokemon = () => {
    const pokemonRight = randomPokemon();
    const pokemonLeft = randomPokemon(pokemonRight);

    return [pokemonRight, pokemonLeft];
  };

  const [pokemonRight, pokemonLeft] = generatePokemon();

  const chosenQuestion = () => {
    const chosenPokemon = [pokemonRData, pokemonLData][
      Math.floor(Math.random() * 2)
    ];
    setSelectedPokemon(chosenPokemon);
    const typeOfQuestion = Math.random() * 1;

    if (typeOfQuestion > 0.7) {
      if (pokemonRData?.legendaryStatus !== pokemonLData?.legendaryStatus) {
        setPokemonQuestion("is a Legendary pokemon?");
      } else if (pokemonRData?.abilities !== pokemonLData?.abilities) {
        setPokemonQuestion(
          "has the ability '" + chosenPokemon?.abilities + "' ?"
        );
      } else if (pokemonRData?.name !== pokemonLData?.name) {
        setPokemonQuestion("has the name '" + chosenPokemon?.name + "' ?");
      }
    } else if (typeOfQuestion > 0.5 && typeOfQuestion < 0.7) {
      if (pokemonRData?.weight !== pokemonLData?.weight) {
        setPokemonQuestion("is heavier ?");
      }
    } else if (typeOfQuestion > 0.25 && typeOfQuestion < 0.5) {
      if (pokemonRData?.height !== pokemonLData?.height) {
        setPokemonQuestion("is taller ?");
      }
    } else if (typeOfQuestion >= 0 && typeOfQuestion < 0.25) {
      if (pokemonRData?.name !== pokemonLData?.name) {
        setPokemonQuestion("has the name '" + chosenPokemon?.name + "' ?");
      }
    }

    console.log(pokemonQuestion);
  };
  const pokeDataFetch = () => {
    axios.get("/api/pokeapi/" + JSON.stringify(pokemonRight)).then((result) => {
      setPokemonRData(result.data);
    });
    axios.get("/api/pokeapi/" + JSON.stringify(pokemonLeft)).then((result) => {
      setPokemonLData(result.data);
    });
  };

  useEffect(() => {
    pokeDataFetch();
  }, []);
  useEffect(() => {
    chosenQuestion();
  }, [pokemonRData, pokemonLData]);

  const winLoseCallback: any = (state: string) => {
    if (state === "win") {
      pokeDataFetch();
    } else {
      console.log("YOU LOSE");
    }
  };
  return (
    <StyledBackgroundContainer>
      <Head>
        <title>The PokeGuess Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TitleBar />
      <PokeGuessApp
        pokemonRImage={pokemonRData.sprite}
        pokemonLImage={pokemonLData.sprite}
        pokemonRName={pokemonRData.name}
        pokemonLName={pokemonLData.name}
        GeneratedQuestion={pokemonQuestion}
        selectedPokemon={selectedPokemon}
        winLose={winLoseCallback}
      />
    </StyledBackgroundContainer>
  );
};

export default Home;
